[common]
enable_documentation = false
enable_introspection = false
developer_mode_fatal_warnings = false
clangd_auto_setup = false
enable_sanitizers = ["address"]
enable_javascript_shell = false
use_system_sysprof_capture = true
enable_wk_web_extensions = false
use_spiel = true
use_flite = false

[gtk]
use_gtk4 = false

[wpe]
enable_cog = true
enable_wpe_qt_api = false