command_timeout = 20000

# Don't print a new line at the start of the prompt
add_newline = false

format = """
$username\
$hostname\
$container\
$directory\
$git_branch\
$git_state\
$git_status\
${env_var.GST_ENV}\
${env_var.WEBKIT_OUTPUTDIR}\
$cmd_duration\
$python\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
# I don't care about untracked files or that there's a stash present.
untracked = ""
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind)]($style)"
style = "cyan"
conflicted = "​"
modified = "​*"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[env_var.GST_ENV]
format = "in gst-env [$env_value]($style)"
style = "green bold"

[env_var.WEBKIT_OUTPUTDIR]
format = "in WebKit [$env_value]($style)"
style = "red bold"
